### ISSUE TITLE
OperationalError when opening .db files

### ISSUE THREAD

**Issue by gpwolfe** [ulissigroup/tmqm_wB97MV#1]
I am following the Contents.ipynb notebook. I have ase installed. When I run the first cell, I get an error: "OperationalError: unable to open database file".  I have tried opening other .db files from the repository and get the same error. Is there possibly a setting that I am missing?

**Comment by jkitchin** [comment]
can you say more about your environment? I can run the first cell in that notebook successfully on a Mac, but I see the same error trying to run it on a Linux machine.

**Comment by jkitchin** [comment]
weird. This works fine:

```
from ase.db import connect
from ase.io import read

db = connect('all_data/removed_structures/removed_structures.db')
entry = db.get(id=1)
structure = read('all_data/removed_structures/removed_structures.db@id=1')

print(structure)
print(entry.data)
```

**Comment by gpwolfe** [comment]
I'm on a Macbook, using Python 3.10. I'm also able to open removed_structures.db with the notebook--
I've just checked with DB Browser for SQLite, as well; removed_structures.db can be opened, but for tmQM_wB97MV.db, DB Browser prompts for a SQLCipher encryption key, and issues an 'invalid file format' error if no key is given.

**Comment by jkitchin** [comment]
@aarongarrison can you take a look at what is happening here?

**Comment by aarongarrison** [comment]
My first thought, if you can open removed_structures.db but none of the other database files, is that you might be trying to use the pointer files from Git LFS instead of the database files themselves. When you installed the repository, did you have Git LFS installed? If not, it might be the case that SQL or the ASE code in the notebook is trying to read the pointer files instead of the databases, which could cause the issues you describe.

**Comment by gpwolfe** [comment]
Missing Git LFS was indeed the problem. Installed LFS and can now read the .db files. Thank you!
