### ISSUE TITLE
Not reference corrected file

### ISSUE THREAD

**Issue by OleksandraOst** [ulissigroup/tmqm_wB97MV#2]
Hello!
I have been using your data from the tmQM and tmQM_wB97MV data folders. 
I am particularly interested in reference corrected lmbd files. However, it seems that tmqm_elec_e_reference_corrected.lmdb and tmqm_wB97MV_elec_e_reference_corrected.lmdb are not reference corrected as the energy distributions from these files are the same as from tmqm_elec_e.lmdb and tmqm_wB97MV_elec_e.lmdb respectively. The same issue occurs with neutral files too.

Please see the example plot attached.
<img width="540" alt="Screenshot 2024-02-23 at 12 10 19" src="https://github.com/ulissigroup/tmQM_wB97MV/assets/53404646/b5eb2f53-8d31-4632-8901-9e6c71a41a94">

**Comment by OleksandraOst** [comment]
Reference correction is done for y_relaxed not for Electronic_E

**Comment by aarongarrison** [comment]
Hi! Thank you for bringing this to our attention - the reference correction script writes a new LMDB that reference corrects the targets, which are stored as `y_relaxed`. Here, the energies are also stored in the LMDBs under the attribute `Electronic_E` for tmQM, or `energy` for tmQM_wB97MV, which is the same for both the `*_elec_e.lmdb` and the `*_elec_e_reference_corrected.lmdb` files. This can be confusing, since those are always the uncorrected energies, and the reference correction is only applied to the target, `y_relaxed`. I have updated the `guides/tmQM_wB97MV Preprocessing.md` file to note this behavior.
